### ISSUE TITLE
Project doesn't compile on v1.75

### ISSUE THREAD

**Issue by kegsay** [matrix-org/matrix-rust-sdk#3224]
```
error[E0658]: use of unstable library feature 'ptr_from_ref'
   --> crates/matrix-sdk/src/event_cache/linked_chunk.rs:868:28
    |
868 |             .field("ptr", &std::ptr::from_ref(self))
    |                            ^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #106116 <https://github.com/rust-lang/rust/issues/106116> for more information
```

The project claims to only need [1.70](https://github.com/matrix-org/matrix-rust-sdk/blob/main/Cargo.toml#L18)

**Comment by andybalaam** [comment]
I think the first thing to do on this is add CI that verifies the minimum supported rust version. The Cargo guide has a recommendation on how to do this: https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version
