### ISSUE TITLE
Toy project fails to build with features = ["testing"] in 0.8.0

### ISSUE THREAD

**Issue by andybalaam** [matrix-org/matrix-rust-sdk#4307]
I am writing a library ([matrix-sdk-redis](https://codeberg.org/andybalaam/matrix-sdk-redis)) that depends on `matrix-rust-sdk` and uses some of its testing facilities, specifically the `cryptostore_integration_tests` macro. Using this macro is critical for me to be able to check whether my crypto store implementation works.

I upgraded the project to matrix-sdk version 0.8.0 today and I get a compile error when I try to compile the tests. Here is a minimal example:

```
$ cat Cargo.toml 
[package]
name = "tmp"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix-sdk = "0.8.0"

[dev-dependencies]
matrix-sdk = { version = "0.8.0", features = ["testing"]}
```

```
$ cat src/main.rs 
fn main() {
    println!("Hello, world!");
}
```

```
$ cargo test
   Compiling matrix-sdk-crypto v0.8.0
error[E0432]: unresolved import `matrix_sdk_test::ruma_response_from_json`
    --> /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/matrix-sdk-crypto-0.8.0/src/identities/manager.rs:1219:9
     |
1219 |     use matrix_sdk_test::ruma_response_from_json;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ruma_response_from_json` in the root

error[E0432]: unresolved import `matrix_sdk_test::ruma_response_from_json`
    --> /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/matrix-sdk-crypto-0.8.0/src/identities/user.rs:1195:9
     |
1195 |     use matrix_sdk_test::ruma_response_from_json;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ruma_response_from_json` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `matrix-sdk-crypto` (lib) due to 2 previous errors
```

I've tried to figure out what's wrong and I can't see why it compiles fine in my checkout of matrix-rust-sdk but not when I depend on it as a library. Any help appreciated!

**Comment by poljar** [comment]
I haven't checked, but probably because we didn't do a release of the `matrix-sdk-test` crate: https://crates.io/crates/matrix-sdk-test.

I'm not sure we should  do so, nor am I sure that the testing feature should exist.

**Comment by andybalaam** [comment]
Yeah, understood, but I would really like some way of running `cryptostore_integration_tests` in my crate, and at the moment I think that needs the `testing` feature.

**Comment by andybalaam** [comment]
This is fixed in matrix-rust-sdk 0.10.0. Thanks!
